# Generated by Django 3.0.7 on 2020-12-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0007_auto_20200817_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='origin_name',
            field=models.CharField(default='origin_name', max_length=30),
        ),
    ]
